MotoActions: define LOCAL_OPTIONAL_USES_LIBRARIES
fixes:
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: []
	- optional libraries in build system: []
	                 vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
	- tags in the manifest (out/target/common/obj/APPS/MotoActions_intermediates/manifest/AndroidManifest.xml):
		<uses-library android:name="androidx.window.extensions" android:required="false"/>
		<uses-library android:name="androidx.window.sidecar" android:required="false"/>

Change-Id: Ie9c9cb579251a96ffaa539a43d988aa4e045f54c
Signed-off-by: William <williamsilvapppl@gmail.com>